export enum SectionType {
    HERO = "HERO",
    ADVANTAGES = "ADVANTAGESGROUP",
    FAQS = "FAQGROUP",
    OFFERS = "OFFERSGROUP",
    PARTNERS = "PARTNERS",
    RICHTEXTWITHCTA = "RICHTEXTWITHCTA",
    TESTIMONIALS = "TESTIMONIALSGROUP",
    PUBLICATIONS = "PUBLICATIONSGROUP"
}